ascensores/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from tienda.sitemap import TiendaViewSitemap
from productos.sitemap import ProductoSitemap
from bienvenida.views import robots_view
from bienvenida.sitemap import BienvenidaViewSitemap
sitemaps = {
    'bienvenida': BienvenidaViewSitemap,
    'tienda': TiendaViewSitemap,
    'productos': ProductoSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    # Redirige la URL raíz al módulo bienvenida.urls
    path("", include('bienvenida.urls')),
    path('accounts/', include('registration.backends.default.urls')),
    path("usuarios/", include('usuarios.urls')),
    path("captcha/", include('captcha.urls')),
    path("tienda/", include ('tienda.urls')),
    path("api/v1.0/", include ('restapi.urls')),
    path("carrito/", include ('carro.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('robots.txt', robots_view, name='robots')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carro/urls.py
from django.urls import path
from carro.views_carrito import Carrito
from carro import views_agregar
from carro import views_quitar

urlpatterns = [
    path("", Carrito.as_view(), name="carrito"),
    path("agregar/", views_agregar.agregar, name="agregar"),
    path("quitar/", views_quitar.quitar, name="quitar"),
]

usuarios/urls.py
# Dejamos la ruta del path
from django.urls import path
# Importamos la función creada
from usuarios import views
from usuarios.views import ModUsuarios

urlpatterns = [
    path('usuarios',ModUsuarios.as_view(), name='usuarios'),
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User #Importo los usuarios registrados en django.
from django.conf import settings
import time

# Create your models here.
class Datousuario (models.Model):
    usuario = models.OneToOneField (User,blank=False, null=True,on_delete=models.CASCADE)
    imagen = models.ImageField (upload_to="producto/%Y/%m/%d", default="defecto=defecto.png", blank=True, null=True)
    fecha_nacimiento = models.DateField (blank=True, null=True)
    pais = models.CharField (max_length=30, blank=True)
    provincia = models.CharField (max_length=40, blank=True)
    ciudad = models.CharField (max_length=40, blank=True)
    domicilio = models.CharField (max_length=80, blank=True)
    codigo_postal = models.CharField (max_length=50, blank=True)
    telefono = models.CharField (max_length=30, blank=True)
    celular = models.CharField (max_length=30, blank=True)
    documento = models.CharField (max_length=30, blank=True)
    cuit = models.CharField (max_length=30, blank=True)

    def __str__(self):
        return self.usuario.username

usuarios/forms.py
from django.forms import ModelForm, DateInput, TextInput, Textarea, Select
from usuarios.models import Datousuario
from django import forms
from django.contrib.auth.models import User

class InfoAdUsuarios(ModelForm):
    imagen = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}), required=False)
    fecha_nacimiento = forms.DateField(
        widget=DateInput(attrs={'class': 'form-control', 'type': 'date'}, format='%Y-%m-%d'),
        required=False
    )
    pais = forms.CharField(widget=TextInput(attrs={'class': 'form-control'}), required=False)
    provincia = forms.CharField(widget=TextInput(attrs={'class': 'form-control'}), required=False)
    ciudad = forms.CharField(widget=TextInput(attrs={'class': 'form-control'}), required=False)
    domicilio = forms.CharField(widget=TextInput(attrs={'class': 'form-control'}), required=False)
    codigo_postal = forms.CharField(widget=TextInput(attrs={'class': 'form-control'}), required=False)
    telefono = forms.CharField(widget=TextInput(attrs={'class': 'form-control'}), required=False)
    celular = forms.CharField(widget=TextInput(attrs={'class': 'form-control'}), required=False)
    documento = forms.RegexField(
        regex=r'^\d+$',
        widget=TextInput(attrs={
            'class': 'form-control',  # <--- ¡Añade la clase aquí!
            'inputmode': 'numeric',   # Para teclados móviles
            'pattern': r'^\d+$'       # Para validación HTML5 del lado del cliente
        }),
        required=False,
        error_messages={'invalid': 'Solo se permiten números en este campo.'},
        label="Documento"
    )
    cuit = forms.CharField(widget=TextInput(attrs={'class': 'form-control'}), required=False)
    
    class Meta:
        model = Datousuario
        fields = [
            'imagen',
            'fecha_nacimiento',
            'pais',
            'provincia',
            'ciudad',
            'domicilio',
            'codigo_postal',
            'telefono',
            'celular',
            'documento',
            'cuit',
        ]
        
    def __init__(self, *args, **kwargs):
        super(InfoAdUsuarios, self).__init__(*args, **kwargs)

class UserForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email=forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))  
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name.label = "Nombre/s"
    last_name.label = "Apellido/s"
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

usuarios/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from usuarios.forms import InfoAdUsuarios, UserForm
from django.contrib import messages
from django.shortcuts import redirect
# Create your views here.
def usuarios (request):
    return HttpResponse ("APP USUARIOS") #Retornamos un mensaje de prueba


class ModUsuarios(View):
    template = 'usuarios/usuarios.html'

    def get(self, request):
        form_adicional = InfoAdUsuarios()
        form_user = UserForm ()
        params = {}
        if request.user.is_authenticated:
            # Si el usuario está autenticado, obtenemos sus datos
            try:
                form_adicional = InfoAdUsuarios(instance=request.user.datousuario)
                form_user = UserForm(instance=request.user)
            except Exception as e:
                print(f"Error al obtener los datos del usuario: {e}")
        params['form_user'] = form_user
        params['form_adicional'] = form_adicional  # Pasa el formset al template en el GET
        return render(request, self.template, params)  
        
    def post(self, request):
        params = {}
        form_adicional = InfoAdUsuarios(request.POST, request.FILES, instance=request.user.datousuario)
        form_user = UserForm(request.POST, instance=request.user)
        params['form_user'] = form_user
        params['form_adicional'] = form_adicional
        if form_adicional.is_valid() and form_user.is_valid():
            form_adicional.save()
            form_user.save()
            messages.success(request, 'Los datos se han actualizado correctamente.')
            print("Datos actualizados correctamente")
            return redirect('usuarios')
            #return render(request, self.template,params)
        
        return render(request, self.template, {'form_user': form_user, 'form_adicional': form_adicional})

templates/usuarios/usuarios.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Usuarios{% endblock %}

{% block contenedor %}

<div class="container" id="baner-contactanos">
    <img src="{% static 'img/baner.png' %}" class="w-100 h-100" id="img-baner" alt="Baner">
</div>

<div id="contenedor-usuarios" class="container p-5">
    <div class="row">
        <div class="col-12">
            <h1>Información de Usuario</h1>
        </div>
        
        <div class="col-12">
            {% if messages %} {# <-- Verifica si hay mensajes #}
                {% for message in messages %} {# <-- Itera sobre cada mensaje #}
                    {# La clase 'alert-{{ message.tags }}' se resolverá a 'alert-success' #}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }} {# <-- Muestra el texto del mensaje #}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        
        <form id="contactForm" action="" method="post" class="row"> {% csrf_token %}
            <div class="col-lg-4">
            {{form_user}}
            {{ form_adicional.fecha_nacimiento.label_tag }}
                {{ form_adicional.fecha_nacimiento }}
                {% if form_adicional.fecha_nacimiento.errors %}
                    <div class="text-danger">{{ form_adicional.fecha_nacimiento.errors }}</div>
                {% endif %}
            </div>
            <div class="col-lg-4">
                {{ form_adicional.pais.label_tag }}
                {{ form_adicional.pais }}
                {% if form_adicional.pais.errors %}
                    <div class="text-danger">{{ form_adicional.pais.errors }}</div>
                {% endif %}

                {{ form_adicional.provincia.label_tag }}
                {{ form_adicional.provincia }}
                {% if form_adicional.provincia.errors %}
                    <div class="text-danger">{{ form_adicional.provincia.errors }}</div>
                {% endif %}

                {{ form_adicional.ciudad.label_tag }}
                {{ form_adicional.ciudad }}
                {% if form_adicional.ciudad.errors %}
                    <div class="text-danger">{{ form_adicional.ciudad.errors }}</div>
                {% endif %}

                {{ form_adicional.domicilio.label_tag }}
                {{ form_adicional.domicilio }}
                {% if form_adicional.domicilio.errors %}
                    <div class="text-danger">{{ form_adicional.domicilio.errors }}</div>
                {% endif %}

                {{ form_adicional.codigo_postal.label_tag }}
                {{ form_adicional.codigo_postal }}
                {% if form_adicional.codigo_postal.errors %}
                    <div class="text-danger">{{ form_adicional.codigo_postal.errors }}</div>
                {% endif %}
            </div>
            <div class="col-lg-4">
                {{ form_adicional.telefono.label_tag }}
                {{ form_adicional.telefono }}
                {% if form_adicional.telefono.errors %}
                    <div class="text-danger">{{ form_adicional.telefono.errors }}</div>
                {% endif %}

                {{ form_adicional.celular.label_tag }}
                {{ form_adicional.celular }}
                {% if form_adicional.celular.errors %}
                    <div class="text-danger">{{ form_adicional.celular.errors }}</div>
                {% endif %}

                {{ form_adicional.documento.label_tag }}
                {{ form_adicional.documento }}
                {% if form_adicional.documento.errors %}
                    <div class="text-danger">{{ form_adicional.documento.errors }}</div>
                {% endif %}

                {{ form_adicional.cuit.label_tag }}
                {{ form_adicional.cuit }}
                {% if form_adicional.cuit.errors %}
                    <div class="text-danger">{{ form_adicional.cuit.errors }}</div>
                {% endif %}
                
                {{ form_adicional.imagen.label_tag }}
                {{ form_adicional.imagen }}
                {% if form_adicional.imagen.errors %}
                    <div class="text-danger">{{ form_adicional.imagen.errors }}</div>
                {% endif %}
            </div>
            
            <div class="col-12 text-center">
                <br>
                <button type="submit" class="btn btn-primary">Enviar</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}
<!--
<div class="col-lg-4">
    <div class="mb-3">
        <label for="id_username" class="form-label">Username:</label>
        <input type="text" name="username" value="Belen" class="form-control" required id="id_username">
    </div>
    <div class="mb-3">
        <label for="id_email" class="form-label">Email:</label>
        <input type="email" name="email" value="belen@gmail.com" class="form-control" required id="id_email">
    </div>
    <div class="mb-3">
        <label for="id_first_name" class="form-label">Nombre/s:</label>
        <input type="text" name="first_name" class="form-control" required id="id_first_name">
    </div>
    <div class="mb-3">
        <label for="id_last_name" class="form-label">Apellido/s:</label>
        <input type="text" name="last_name" class="form-control" required id="id_last_name">
    </div>
    <div class="mb-3">
        <label for="id_imagen" class="form-label">Imagen:</label>
        <input type="file" name="imagen" class="form-control" accept="image/*" id="id_imagen">
    </div>
    <div class="mb-3">
        <label for="id_fecha_nacimiento" class="form-label">Fecha nacimiento:</label>
        <input type="date" name="fecha_nacimiento" class="form-control" required id="id_fecha_nacimiento">
    </div>
    <div class="mb-3">
        <label for="id_telefono" class="form-label">Telefono:</label>
        <input type="text" name="telefono" class="form-control" required id="id_telefono">
    </div>
    <div class="mb-3">
        <label for="id_celular" class="form-label">Celular:</label>
        <input type="text" name="celular" class="form-control" required id="id_celular">
    </div>
    <div class="mb-3">
        <label for="id_documento" class="form-label">Documento:</label>
        <input type="text" name="documento" class="form-control" required id="id_documento">
    </div>
    <div class="mb-3">
        <label for="id_cuit" class="form-label">Cuit:</label>
        <input type="text" name="cuit" class="form-control" required id="id_cuit">
    </div>
</div>
-->

templates/usuarios/usuarios_copy.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Usuarios{% endblock %}

{% block contenedor %}

<div class="container" id="baner-contactanos">
    <img src="{% static 'img/baner.png' %}" class="w-100 h-100" id="img-baner" alt="Baner">
</div>

<div id="contenedor-contactanos" class="container p-5">
    <div class="row">
        <div class="col-12">
            <h1>Información de Usuario</h1>
        </div>
        <form id="contactForm" action="" method="post" class="row"> {% csrf_token %}
            <div class="col-lg-4">
            {{form_user}}
            {{form_adicional}}
            </div>
            
            <div class="col-12 text-center">
                <br>
                <button type="submit" class="btn btn-primary">Enviar</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}
<!--
<div class="col-lg-4">
    <div class="mb-3">
        <label for="id_username" class="form-label">Username:</label>
        <input type="text" name="username" value="Belen" class="form-control" required id="id_username">
    </div>
    <div class="mb-3">
        <label for="id_email" class="form-label">Email:</label>
        <input type="email" name="email" value="belen@gmail.com" class="form-control" required id="id_email">
    </div>
    <div class="mb-3">
        <label for="id_first_name" class="form-label">Nombre/s:</label>
        <input type="text" name="first_name" class="form-control" required id="id_first_name">
    </div>
    <div class="mb-3">
        <label for="id_last_name" class="form-label">Apellido/s:</label>
        <input type="text" name="last_name" class="form-control" required id="id_last_name">
    </div>
    <div class="mb-3">
        <label for="id_imagen" class="form-label">Imagen:</label>
        <input type="file" name="imagen" class="form-control" accept="image/*" id="id_imagen">
    </div>
    <div class="mb-3">
        <label for="id_fecha_nacimiento" class="form-label">Fecha nacimiento:</label>
        <input type="date" name="fecha_nacimiento" class="form-control" required id="id_fecha_nacimiento">
    </div>
    <div class="mb-3">
        <label for="id_telefono" class="form-label">Telefono:</label>
        <input type="text" name="telefono" class="form-control" required id="id_telefono">
    </div>
    <div class="mb-3">
        <label for="id_celular" class="form-label">Celular:</label>
        <input type="text" name="celular" class="form-control" required id="id_celular">
    </div>
    <div class="mb-3">
        <label for="id_documento" class="form-label">Documento:</label>
        <input type="text" name="documento" class="form-control" required id="id_documento">
    </div>
    <div class="mb-3">
        <label for="id_cuit" class="form-label">Cuit:</label>
        <input type="text" name="cuit" class="form-control" required id="id_cuit">
    </div>
</div>
-->